version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s

  app:
    build: .
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        poetry run litestar database upgrade --no-prompt &&
        poetry run uvicorn app:app --host 0.0.0.0 --port 8000
      "

volumes:
  pgdata:
